#!/usr/bin/env python3
"""Generate appendix_permonth.tex from final_results.json.

Same data source and same seed-mean treatment as Figures 5.4/5.5
(scripts/make_ch5_figures.py), so the appendix numbers match the body.
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
RES = HERE.parent.parent / "experiments" / "final_v2" / "results"
OUT = HERE / "appendix_permonth.tex"


def main() -> None:
    j = json.loads((RES / "final_results.json").read_text())
    block = j["results"]["S3_wealth"]
    print("provenance:", j.get("provenance"))

    months = [m["id"] for m in block["baselines"]["B1b_true_bah"]["per_month"]]
    bah = [m["delta_w"] for m in block["baselines"]["B1b_true_bah"]["per_month"]]
    slc = [m["delta_w"] for m in block["baselines"]["B1a_slice_bah"]["per_month"]]

    algo_means = {}
    for algo in ("reinforce", "dqn", "ppo"):
        per_seed = block["algos"][algo]["per_seed"]
        algo_means[algo] = [
            sum(s["per_month"][k]["delta_w"] for s in per_seed) / len(per_seed)
            for k in range(len(months))
        ]

    for name, vals in [("bah", bah), ("always-buy", slc)] + list(algo_means.items()):
        print(f"{name}: mean {sum(vals)/len(vals):+.2f}")

    lines = [
        "% Generated by make_appendix_permonth.py from final_results.json.",
        "% Do not edit by hand; rerun the script instead.",
        "",
        "Wealth change \\(\\Delta W\\) in dollars for every held-out test",
        "month (\\(C_0 = \\$10{,}000\\), 0.25\\,\\(C_0\\) trade size, 0.05\\%",
        "fee, wealth-change reward). Learned columns are the mean of the six",
        "training seeds, so they match the seed means reported in",
        "Section~5.6. The final row is the sum over the 24 months.",
        "",
        r"\begin{longtable}{@{}lrrrrr@{}}",
        r"\toprule",
        r"\textbf{Month} & \textbf{Buy-and-hold} & \textbf{Always-buy"
        r" (\(0.25\,C_0\))} & \textbf{REINFORCE} & \textbf{DQN} & \textbf{PPO} \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"\textbf{Month} & \textbf{Buy-and-hold} & \textbf{Always-buy"
        r" (\(0.25\,C_0\))} & \textbf{REINFORCE} & \textbf{DQN} & \textbf{PPO} \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    for k, month in enumerate(months):
        row = [month] + [
            f"{v:+.2f}"
            for v in (bah[k], slc[k], algo_means['reinforce'][k],
                      algo_means['dqn'][k], algo_means['ppo'][k])
        ]
        lines.append(" & ".join(row) + r" \\")
    lines.append(r"\midrule")
    totals = [sum(bah), sum(slc), sum(algo_means['reinforce']),
              sum(algo_means['dqn']), sum(algo_means['ppo'])]
    lines.append(r"\textbf{Total} & " +
                 " & ".join(f"\\textbf{{{t:+.2f}}}" for t in totals) + r" \\")
    lines.append(r"\end{longtable}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.name}")


if __name__ == "__main__":
    main()
