"""Generate the per-year transfer table for Appendix C from sim_results.json.

For every calendar year in the 180-month transfer set, sums the monthly
wealth changes of buy-and-hold, always-buy, and the six-seed mean of each
learned agent. Writes latex/dissertation/appendix_transfer_table.tex,
which appendix_permonth.tex inputs.
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "experiments" / "final_v2" / "results" / "sim_results.json"
OUT = ROOT / "latex" / "dissertation" / "appendix_transfer_table.tex"

ALGOS = ("reinforce", "dqn", "ppo")


def yearly(per_month: list[dict]) -> dict[str, float]:
    out: dict[str, float] = defaultdict(float)
    for row in per_month:
        out[row["id"][:4]] += row["delta_w"]
    return out


def agent_yearly_mean(seeds: list[dict]) -> dict[str, float]:
    per_seed = [yearly(s["real_per_month"]) for s in seeds]
    years = per_seed[0].keys()
    return {y: sum(p[y] for p in per_seed) / len(per_seed) for y in years}


def fmt(v: float) -> str:
    sign = "+" if v >= 0 else "-"
    return f"{sign}{abs(v):,.2f}"


def main() -> None:
    j = json.loads(RESULTS.read_text())
    bah = yearly(j["baselines_real"]["B1b_true_bah"]["per_month"])
    ab = yearly(j["baselines_real"]["B1a_slice_bah"]["per_month"])
    agents = {a: agent_yearly_mean(j["results"][a]["per_seed"]) for a in ALGOS}

    years = sorted(bah.keys())
    lines = [
        "% Generated by scripts/make_appendix_transfer.py from sim_results.json.",
        "% Do not hand-edit; rerun the script instead.",
        r"\begin{longtable}{@{}lrrrrr@{}}",
        r"\toprule",
        r"\textbf{Year} & \textbf{Buy-and-hold} & \textbf{Always-buy (\(0.25\,C_0\))} & \textbf{REINFORCE} & \textbf{DQN} & \textbf{PPO} \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"\textbf{Year} & \textbf{Buy-and-hold} & \textbf{Always-buy (\(0.25\,C_0\))} & \textbf{REINFORCE} & \textbf{DQN} & \textbf{PPO} \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    for y in years:
        row = [y, fmt(bah[y]), fmt(ab[y])] + [
            fmt(agents[a][y]) for a in ALGOS
        ]
        lines.append(" & ".join(row) + r" \\")
    total = lambda d: sum(d[y] for y in years)  # noqa: E731
    lines.append(r"\midrule")
    lines.append(
        r"\textbf{Total} & "
        + " & ".join(
            rf"\textbf{{{fmt(v)}}}"
            for v in (
                total(bah),
                total(ab),
                total(agents["reinforce"]),
                total(agents["dqn"]),
                total(agents["ppo"]),
            )
        )
        + r" \\"
    )
    lines.append(r"\end{longtable}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(years)} years)")


if __name__ == "__main__":
    main()
